function jm_automate_rerun_virt_sim_from_params_intrinsic_vs_driven_freq (varargin)
%% Automate re-running vIRt simulations from extracted parameters
% Usage: jm_automate_rerun_virt_sim_from_params_intrinsic_vs_driven_freq (varargin)
% Explanation:
%       This function loads a previously generated "External Current" simulation
%       dataset, extracts parameters corresponding to specific simulation 
%       indices (representing specific combos of Mean/Std/FMN currents), 
%       and re-runs them using the "Replicates" workflow.
%
%       The goal is to take specific points of interest from a broad parameter
%       sweep and perform a more detailed frequency/variability analysis 
%       (intrinsic vs driven) on those specific network configurations.
%
% Inputs:
%       Most recent simulation data file matching pattern: 'simData_ExtCurrent_*.mat'
%           that is generated by jm_automate_virt_sim_vary_ext_current.m
%
% Outputs:
%       This creates the outputs
%           simData_vary_freq_ExtCurrentSims_inputSet1.mat
%           ...
%           simData_vary_freq_ExtCurrentSims_inputSetN.mat
%       required for jm_postprocess_virt_sim_amplitude_analysis_ExtCurrentRuns.m
%       which produces Figure 7b - 7e in Lu et al 2026
%
% Arguments:
%       varargin    - 'SimDataFile': Path to the source .mat file containing 
%                     previous simulation results (ExtCurrent sweep).
%                   must be a string scalar or a character vector
%                   default == (Most recent 'simData_ExtCurrent_*.mat')
%                   - 'SimulationDir': Directory containing the simulation code.
%                   must be a string scalar or a character vector
%                   default == pwd
%                   - 'ExtCurrentSimIndices': Matrix of indices to select 
%                     simulations to re-run. Columns: [vIRtMean, vIRtStd, FMNMean].
%                   must be a numeric matrix
%                   default == (Hardcoded matrix in script)
%                   - 'SimDur': Simulation duration in ms.
%                   must be a positive numeric scalar
%                   default == 30000
%                   - 'IntrinsicProbePeriod': Probe period (ms).
%                   must be a positive numeric scalar
%                   default == 200
%                   - 'TestFrequencies': Vector of frequencies to test (Hz).
%                   must be a numeric vector
%                   default == 1:0.25:10
%                   - 'TestPerVar': Vector of period variabilities to test.
%                   must be a numeric vector
%                   default == 0
%                   - 'NumRandomSims': Number of randomized replicates.
%                   must be a non-negative integer scalar
%                   default == 0
%                   - 'OutDir': Directory to save output .mat files.
%                   must be a string scalar or a character vector
%                   default == pwd
%                   - 'RngAlgorithm': The random number generator algorithm to use.
%                       Options: 'twister', 'simdTwister', 'combRecursive',
%                                'multFibonacci', 'philox', 'threefry',
%                                'v4', 'v5uniform', 'v5normal'
%                   must be a string scalar or a character vector
%                   default == [] (set in virt_moore_params.m)
%
% Requires:
%       \Shared\Code\Adams_Functions\archive_dependent_scripts.m
%       \Shared\Code\vIRt-Moore\jm_run_virt_sim_replicates.m
%
% Used by:
%       (User automated scripts)

% File History:
% 2025-11-21 Created by Jeff Moore
% 2025-12-08 Last updated before rerun
% 2026-01-09 Updated to point to new 20260109 dataset.
% 2026-01-13 Refactored by Gemini to match vIRt coding standards.
% 2026-01-16 Now archives dependent scripts
% 2026-01-16 Now detects input files using pattern matching
% 2026-01-18 Added 'RngAlgorithm' optional argument
% 2026-01-21 Fixed pOrig backwards compatibility and variable consistency

%% Hard-Coded Information For This Script Only
% Default Simulation Data File Pattern
simDataFilePattern = 'simData_ExtCurrent_*.mat';

% Default Indices to Run [virtInputInd, virtStdTimeInd, fmnInputInd]
% Rationale: These points correspond to specific frequencies of interest
% found in the sweep (e.g., 5.5 Hz, 6.0 Hz, etc.)
extCurrentSimIndicesDefault = [ ...
    1, 4, 1; ...    % ~5.5 Hz
    3, 5, 2; ...    % ~6.0 Hz
    4, 6, 3; ...    % ~6.6 Hz
    5, 6, 3; ...    % ~7.1 Hz
    6, 7, 4; ...    % ~7.5 Hz
    10, 9, 6; ...   % ~7.8 Hz
    11, 10, 6; ...  % ~8.4 Hz
    14, 12, 8; ...  % ~8.9 Hz
    ];
    
validRngAlgorithms = {'twister', 'simdTwister', 'combRecursive', ...
                      'multFibonacci', 'philox', 'threefry', ...
                      'v4', 'v5uniform', 'v5normal'};

%% Default values for optional arguments
simDataFileDefault = '';            % auto-detected based on simDataFilePattern
simulationDirDefault = pwd;
simDurDefault = 30000;              % simulation duration
intrinsicProbePeriodDefault = 200;  % probe period
testFrequenciesDefault = 1:0.25:10; % frequencies to test
testPerVarDefault = 0;              % period variability
numRandomSimsDefault = 0;           % number of random simulations
outDirDefault = pwd;                % save to current directory
rngAlgorithmDefault = [];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Deal with arguments
% Set up Input Parser Scheme
iP = inputParser;
iP.FunctionName = mfilename;
iP.KeepUnmatched = false;

% Add parameter-value pairs to the Input Parser
addParameter(iP, 'SimDataFile', simDataFileDefault, ...
    @(x) validateattributes(x, {'char', 'string'}, {'scalartext'}));
addParameter(iP, 'SimulationDir', simulationDirDefault, ...
    @(x) validateattributes(x, {'char', 'string'}, {'scalartext'}));
addParameter(iP, 'ExtCurrentSimIndices', extCurrentSimIndicesDefault, ...
    @(x) validateattributes(x, {'numeric'}, {'matrix', 'ncols', 3}));
addParameter(iP, 'SimDur', simDurDefault, ...
    @(x) validateattributes(x, {'numeric'}, {'scalar', 'positive'}));
addParameter(iP, 'IntrinsicProbePeriod', intrinsicProbePeriodDefault, ...
    @(x) validateattributes(x, {'numeric'}, {'scalar', 'positive'}));
addParameter(iP, 'TestFrequencies', testFrequenciesDefault, ...
    @(x) validateattributes(x, {'numeric'}, {'vector'}));
addParameter(iP, 'TestPerVar', testPerVarDefault, ...
    @(x) validateattributes(x, {'numeric'}, {'vector'}));
addParameter(iP, 'NumRandomSims', numRandomSimsDefault, ...
    @(x) validateattributes(x, {'numeric'}, {'scalar', 'integer', 'nonnegative'}));
addParameter(iP, 'OutDir', outDirDefault, ...
    @(x) validateattributes(x, {'char', 'string'}, {'scalartext'}));
addParameter(iP, 'RngAlgorithm', rngAlgorithmDefault, ...
    @(x) isempty(x) || any(validatestring(x, validRngAlgorithms)));

% Parse the inputs
parse(iP, varargin{:});
simDataFile = iP.Results.SimDataFile;
simulationDir = iP.Results.SimulationDir;
extCurrentSimIndices = iP.Results.ExtCurrentSimIndices;
simDur = iP.Results.SimDur;
intrinsicProbePeriod = iP.Results.IntrinsicProbePeriod;
testFrequencies = iP.Results.TestFrequencies;
testPerVar = iP.Results.TestPerVar;
numRandomSims = iP.Results.NumRandomSims;
outDir = iP.Results.OutDir;
rngAlgorithm = iP.Results.RngAlgorithm;

% Ensure output directory exists
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

% Copy this script and its dependencies to the output directory
archive_dependent_scripts(mfilename, 'OutFolder', outDir);

%% Preparation
if isempty(simDataFile)
    % Find all data files matching desired pattern in outDir
    fileList = dir(fullfile(outDir, simDataFilePattern));
    if isempty(fileList)
        error('No files found matching pattern: %s', simDataFilePattern);
    else
        % Sort by date (descending) to get the most recent file
        [~, idx] = sort([fileList.datenum], 'descend');
        simDataFile = fullfile(fileList(idx(1)).folder, fileList(idx(1)).name);
        fprintf('Auto-detected most recent data file: %s\n', simDataFileDefault);
    end
end

% Load source data
fprintf('Loading source data from: %s\n', simDataFile);
if ~exist(simDataFile, 'file')
    error('Source data file does not exist: %s\nEnsure you provided the correct filename or that a file matching "simData_ExtCurrent_*.mat" exists.', simDataFile);
end

loadedData = load(simDataFile);
fprintf('Data loaded successfully.\n');

% Extract necessary variables from the loaded file
% We need pOrig to restore original pulse width/amplitude settings
% Backwards compatibility: check for Porig (old) or pOrig (new)
if isfield(loadedData, 'pOrig')
    pOrig = loadedData.pOrig;
elseif isfield(loadedData, 'Porig')
    pOrig = loadedData.Porig;
else
    error('Data file must contain "pOrig" or "Porig".');
end

% We need output to extract specific simulation parameters
if isfield(loadedData, 'output')
    dat = loadedData.output;
else
    error('Data file must contain "output".');
end

% Extract sweep vectors for saving later
% Robust check for camelCase (new) vs snake_case (legacy) variable names
if isfield(loadedData, 'vIRtInputCurrents')
    vIRtInputCurrents = loadedData.vIRtInputCurrents;
elseif isfield(loadedData, 'vIRt_input_currents')
    vIRtInputCurrents = loadedData.vIRt_input_currents;
else
    vIRtInputCurrents = [];
end

if isfield(loadedData, 'vIRtStdTimes')
    vIRtStdTimes = loadedData.vIRtStdTimes;
elseif isfield(loadedData, 'vIRt_stdTimes')
    vIRtStdTimes = loadedData.vIRt_stdTimes;
else
    vIRtStdTimes = [];
end

if isfield(loadedData, 'fmnInputCurrents')
    fmnInputCurrents = loadedData.fmnInputCurrents;
elseif isfield(loadedData, 'FMN_input_currents')
    fmnInputCurrents = loadedData.FMN_input_currents;
else
    fmnInputCurrents = [];
end

% Define temporary parameter file name
tempParamFile = fullfile(outDir, 'tempParams.mat');

%% Simulation Loop
nSims = size(extCurrentSimIndices, 1);
fprintf('Starting re-run of %d selected simulations...\n', nSims);

for iSim = 1:nSims
    fprintf('--- Processing Simulation %d of %d ---\n', iSim, nSims);
    
    % Get indices corresponding to external current input params
    virtInputInd = extCurrentSimIndices(iSim, 1);    % vIRt external input current mean
    virtStdTimeInd = extCurrentSimIndices(iSim, 2);  % vIRt external input current std
    fmnInputInd = extCurrentSimIndices(iSim, 3);     % FMN external input current mean
    
    fprintf('   Indices: vIRtInputMeanIdx=%d, vIRtInputStdIdx=%d, FMNInputIdx=%d\n', ...
        virtInputInd, virtStdTimeInd, fmnInputInd);

    % Extract parameters structure from the specific run in the loaded data
    try
        P = dat.intrinsicDefault.vIRtInput(virtInputInd). ...
            vIRtStdTime(virtStdTimeInd).FMNInput(fmnInputInd).params;
    catch ME
        warning('Failed to extract parameters for index set %d. Skipping. Error: %s', ...
            iSim, ME.message);
        continue;
    end
    
    % Restore Pb amplitude and pulse width from original base simulation (pOrig)
    % The extracted 'P' might have modified these during the sweep
    P.SquareInput.Pb.amplitude = pOrig.SquareInput.Pb.amplitude;
    P.SquareInput.Pb.pulseWidth = pOrig.SquareInput.Pb.pulseWidth;
    P.SquareInput.Pb.toRecompute = true;
    
    % Save parameters to a temporary file
    % automation code expects a file with parameters stored in structure 'P'
    save(tempParamFile, 'P');
    
    % Run the replicates simulation
    % This function handles the intrinsic vs driven frequency sweep logic
    fprintf('   > Running simulation replicates...\n');
    [output, pOrig] = jm_run_virt_sim_replicates(simulationDir, ...
                                                 tempParamFile, ...
                                                 simDur, ...
                                                 intrinsicProbePeriod, ...
                                                 testFrequencies, ...
                                                 testPerVar, ...
                                                 numRandomSims, ...
                                                 'RngAlgorithm', rngAlgorithm);
                                             
    % Construct filename for saving
    saveFileName = fullfile(outDir, ...
        sprintf('simData_vary_freq_ExtCurrentSims_inputSet%d.mat', iSim));
    
    fprintf('   > Saving results to: %s\n', saveFileName);
    
    % Save outputs (using -v7.3 for large data support)
    % Preserving all context variables from original script
    % Note: pOrig used by jm_run_virt_sim_replicates is saved here
    save(saveFileName, 'simDataFile', 'testFrequencies', 'testPerVar', ...
         'output', 'pOrig', 'vIRtInputCurrents', 'vIRtStdTimes', ...
         'fmnInputCurrents', 'virtInputInd', 'virtStdTimeInd', ...
         'fmnInputInd', '-v7.3');
     
    fprintf('Simulation %d complete.\n\n', iSim);
end

% Cleanup
if exist(tempParamFile, 'file')
    delete(tempParamFile);
end

fprintf('All automated re-runs complete.\n');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%{
OLD CODE:

%}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%